#!/bin/bash
# ==============================================================================
# Automated Huge Pages Configuration Script (v3)
# ==============================================================================
#
# Description:
# This script automatically:
# 1. Calculates the required number of Huge Pages for MariaDB and PHP OPcache.
# 2. Creates a kernel configuration file to reserve the pages.
# 3. Modifies MariaDB and PHP configurations to use Huge Pages.
#
# Usage:
#   sudo ./setup_hugepages.sh <php_version>
#   Example: sudo ./setup_hugepages.sh php83
#
# Author: Boris Lucas
# Date: June 15, 2025
#
# ==============================================================================

# --- Function to display messages ---
log() {
    echo "[INFO] $1"
}

error() {
    echo "[ERROR] $1" >&2
    exit 1
}

# --- Permission Check ---
if [ "$(id -u)" -ne 0 ]; then
    error "This script must be run with root privileges. Please use sudo."
fi

# --- Argument Check for PHP Version ---
if [ -z "$1" ]; then
    echo "[ERROR] Missing PHP version argument."
    echo ""
    echo "Usage: sudo $0 <php_version>"
    echo "Example: sudo $0 php83"
    echo ""
    AVAILABLE_VERSIONS=$(for dir in /usr/local/lsws/lsphp*; do if [ -d "$dir" ]; then basename "$dir" | sed 's/ls//'; fi; done | tr '\n' ' ')
    if [ -n "$AVAILABLE_VERSIONS" ]; then
        echo "Detected available PHP versions: ${AVAILABLE_VERSIONS}"
    else
        echo "No OpenLiteSpeed PHP versions found in /usr/local/lsws/"
    fi
    exit 1
fi

PHP_TARGET_VERSION_SHORT=${1#php} # Extracts '83' from 'php83'
PHP_INI_PATH="/usr/local/lsws/lsphp${PHP_TARGET_VERSION_SHORT}/etc/php.ini"

if [ ! -f "$PHP_INI_PATH" ]; then
    error "PHP configuration file not found at '$PHP_INI_PATH'. Please check the version name and ensure it's an OLS PHP version."
fi


# --- Find MariaDB/MySQL configuration file ---
MY_CNF="/etc/my.cnf"
if [ ! -f "$MY_CNF" ]; then
    error "MariaDB/MySQL configuration file not found at $MY_CNF. Please ensure MariaDB is installed."
fi

# --- Function to parse memory values (e.g., 8G, 8192M, 1024K) and convert to MB ---
parse_memory_to_mb() {
    local mem_value=$1
    if [[ -z "$mem_value" ]] || [[ "$mem_value" =~ ^[a-zA-Z]+$ ]]; then
        echo 0
        return
    fi
    local value=${mem_value//[^0-9]/}
    local unit=${mem_value//[0-9]/}

    unit=$(echo "$unit" | tr '[:lower:]' '[:upper:]')

    case "$unit" in
        G|GB)
            echo $((value * 1024))
            ;;
        M|MB)
            echo $value
            ;;
        K|KB)
            echo $((value / 1024))
            ;;
        *)
            echo $value
            ;;
    esac
}

# --- Get MariaDB InnoDB Buffer Pool Size ---
log "Reading MariaDB configuration from $MY_CNF..."
INNODB_BUFFER_POOL_SIZE_RAW=$(grep -E "^innodb_buffer_pool_size" "$MY_CNF" | awk -F'=' '{print $2}' | tr -d '[:space:]')

if [ -z "$INNODB_BUFFER_POOL_SIZE_RAW" ]; then
    error "Could not find 'innodb_buffer_pool_size' in $MY_CNF."
fi

INNODB_BUFFER_POOL_MB=$(parse_memory_to_mb "$INNODB_BUFFER_POOL_SIZE_RAW")
log "Detected InnoDB Buffer Pool Size: ${INNODB_BUFFER_POOL_SIZE_RAW} (~${INNODB_BUFFER_POOL_MB} MB)"

# --- Get PHP OPcache Settings ---
log "Reading PHP OPcache configuration from $PHP_INI_PATH..."

OPCACHE_MEM_RAW=$(grep -E "^opcache.memory_consumption" "$PHP_INI_PATH" | awk -F'=' '{print $2}' | tr -d '[:space:]')
OPCACHE_MEM_MB=$(parse_memory_to_mb "${OPCACHE_MEM_RAW:-128M}")
log "Detected OPcache Memory Consumption: ${OPCACHE_MEM_RAW:-128M} (~${OPCACHE_MEM_MB} MB)"

OPCACHE_JIT_RAW=$(grep -E "^opcache.jit_buffer_size" "$PHP_INI_PATH" | awk -F'=' '{print $2}' | tr -d '[:space:]')
OPCACHE_JIT_MB=$(parse_memory_to_mb "${OPCACHE_JIT_RAW:-0M}")
log "Detected OPcache JIT Buffer Size: ${OPCACHE_JIT_RAW:-0M} (~${OPCACHE_JIT_MB} MB)"

# --- Calculate Total Huge Pages Needed ---
log "Calculating total Huge Pages required..."

PHP_OVERHEAD_MB=64
TOTAL_MEMORY_MB=$((INNODB_BUFFER_POOL_MB + OPCACHE_MEM_MB + OPCACHE_JIT_MB + PHP_OVERHEAD_MB))
log "Total memory to cover with Huge Pages: ${TOTAL_MEMORY_MB} MB"

HUGEPAGE_SIZE_KB=$(grep 'Hugepagesize' /proc/meminfo | awk '{print $2}')
if [ -z "$HUGEPAGE_SIZE_KB" ]; then
    HUGEPAGE_SIZE_KB=2048
fi
log "Detected Kernel Hugepagesize: ${HUGEPAGE_SIZE_KB} KB"

NUM_HUGEPAGES=$(( (TOTAL_MEMORY_MB * 1024) / HUGEPAGE_SIZE_KB + 1 ))
log "Calculated number of Huge Pages to reserve: ${NUM_HUGEPAGES}"

# --- Configure Kernel ---
log "Creating sysctl configuration file at /etc/sysctl.d/98-hugepages.conf..."
SYSCTL_CONF_FILE="/etc/sysctl.d/98-hugepages.conf"
echo "# --- Huge Pages Configuration (Generated by Script) ---" > "$SYSCTL_CONF_FILE"
echo "vm.nr_hugepages = ${NUM_HUGEPAGES}" >> "$SYSCTL_CONF_FILE"

# --- Configure MariaDB ---
if grep -q "^large-pages" "$MY_CNF"; then
    log "'large-pages' directive already present in $MY_CNF. No changes made."
else
    log "Adding 'large-pages=1' and comments to the [mysqld] section in $MY_CNF..."
    
    # Step 1: Add the main directive after the [mysqld] line.
    sed -i '/\[mysqld\]/a large-pages=1' "$MY_CNF"
    
    # Step 2: Add the comment BEFORE the new large-pages line.
    sed -i '/^large-pages=1/i # Enable Huge Pages for MariaDB (Added by script)' "$MY_CNF"
    
    # Step 3: Add the comment AFTER the new large-pages line.
    sed -i '/^large-pages=1/a # End of Huge Pages directive (Added by script)' "$MY_CNF"
fi

# --- Configure PHP ---
if grep -q "^opcache.huge_code_pages" "$PHP_INI_PATH"; then
    log "'opcache.huge_code_pages' directive already present in $PHP_INI_PATH. No changes made."
else
    log "Adding 'opcache.huge_code_pages=1' to the [opcache] section in $PHP_INI_PATH..."
    if grep -q "\[opcache\]" "$PHP_INI_PATH"; then
        sed -i '/\[opcache\]/a opcache.huge_code_pages=1' "$PHP_INI_PATH"
    else
        log "No [opcache] section found. Appending to the end of $PHP_INI_PATH."
        echo "" >> "$PHP_INI_PATH"
        echo "[opcache]" >> "$PHP_INI_PATH"
        echo "opcache.huge_code_pages=1" >> "$PHP_INI_PATH"
    fi
fi

# --- Apply settings to the live system ---
log "Applying kernel settings to the current session..."
sysctl -p "$SYSCTL_CONF_FILE"

# --- Final Instructions ---
echo
echo "========================================================================"
echo "    >>> AUTOMATED HUGE PAGES CONFIGURATION COMPLETE <<<"
echo "========================================================================"
echo
echo "The script has performed the following actions:"
echo "1. Configured the kernel to reserve ${NUM_HUGEPAGES} Huge Pages on the next boot."
echo "2. Attempted/Added 'large-pages=1' to your MariaDB configuration."
echo "3. Attempted/Added 'opcache.huge_code_pages=1' to your PHP configuration."
echo
echo "!! IMPORTANT: PLEASE VERIFY BEFORE REBOOTING !!"
echo
echo "Please manually check the following files to ensure the directives were added correctly:"
echo "  - MariaDB Config: cat $MY_CNF (Look for 'large-pages=1' under [mysqld])"
echo "  - PHP Config: cat $PHP_INI_PATH (Look for 'opcache.huge_code_pages=1' under [opcache])"
echo
echo "Once you have verified the settings, a reboot is required to finalize the process."
echo "Run the command: sudo reboot"
echo
echo "========================================================================"

